name: Deploy Daemon RazorUI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MySolution.sln'

    runs-on: ubuntu-latest


    steps:
        - uses: actions/checkout@v4

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5

        - name: Restore dependencies
          run: nuget restore

        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.100-rc.2.23502.2'

        - uses: actions/cache@v3
          with:
            path: ~/.nuget/packages
            # Look to see if there is a cache hit for the corresponding requirements file
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
            restore-keys: |
              ${{ runner.os }}-nuget

        - name: Install dependencies
          run: dotnet add package Microsoft.AspNetCore.Components.QuickGrid --version 8.0.0-rc.2.23480.2
  
        - name: Build with dotnet
          run: dotnet build --configuration Release